package com.jawharat.manifest.utils

import com.joelkanyi.jcomposecountrycodepicker.data.Country
import com.joelkanyi.jcomposecountrycodepicker.resources.Res
import com.joelkanyi.jcomposecountrycodepicker.resources.*

val allCountries: List<Country> = listOf(
    Country("af", "+93", "أفغاني", Res.drawable.af),
    Country("ax", "+358", "آلاندي", Res.drawable.ax),
    Country("al", "+355", "ألباني", Res.drawable.al),
    Country("dz", "+213", "جزائري", Res.drawable.dz),
    Country("as", "+1", "ساموي أمريكي", Res.drawable.`as`),
    Country("ad", "+376", "أندوري", Res.drawable.ad),
    Country("ao", "+244", "أنغولي", Res.drawable.ao),
    Country("ai", "+1", "أنغيلي", Res.drawable.ai),
    Country("aq", "+672", "أنتاركتيكي", Res.drawable.aq),
    Country("ag", "+1", "أنتيغوي", Res.drawable.ag),
    Country("ar", "+54", "أرجنتيني", Res.drawable.ar),
    Country("am", "+374", "أرميني", Res.drawable.am),
    Country("aw", "+297", "أروبي", Res.drawable.aw),
    Country("au", "+61", "أسترالي", Res.drawable.au),
    Country("at", "+43", "نمساوي", Res.drawable.at),
    Country("az", "+994", "أذربيجاني", Res.drawable.az),
    Country("bs", "+1", "باهامي", Res.drawable.bs),
    Country("bh", "+973", "بحريني", Res.drawable.bh),
    Country("bd", "+880", "بنغلاديشي", Res.drawable.bd),
    Country("bb", "+1", "بربادوسي", Res.drawable.bb),
    Country("by", "+375", "بيلاروسي", Res.drawable.by),
    Country("be", "+32", "بلجيكي", Res.drawable.be),
    Country("be", "+32", "بلجيكي", Res.drawable.be),
    Country("bz", "+501", "بليزي", Res.drawable.bz),
    Country("bj", "+229", "بنيني", Res.drawable.bj),
    Country("bm", "+1", "برمودي", Res.drawable.bm),
    Country("bt", "+975", "بوتاني", Res.drawable.bt),
    Country("bo", "+591", "بوليفي", Res.drawable.bo),
    Country("bq", "+599", "بونيري", Res.drawable.bq),
    Country("ba", "+387", "بوسني", Res.drawable.ba),
    Country("bw", "+267", "بوتسواني", Res.drawable.bw),
    Country("bv", "+47", "بوفيتي", Res.drawable.bv),
    Country("br", "+55", "برازيلي", Res.drawable.br),
    Country("io", "+246", "هندي بريطاني", Res.drawable.io),
    Country("bn", "+673", "بروني", Res.drawable.bn),
    Country("bg", "+359", "بلغاري", Res.drawable.bg),
    Country("bf", "+226", "بوركيني", Res.drawable.bf),
    Country("bi", "+257", "بوروندي", Res.drawable.bi),
    Country("cv", "+238", "رأس أخضري", Res.drawable.cv),
    Country("kh", "+855", "كمبودي", Res.drawable.kh),
    Country("cm", "+237", "كاميروني", Res.drawable.cm),
    Country("ca", "+1", "كندي", Res.drawable.ca),
    Country("ky", "+1", "كايماني", Res.drawable.ky),
    Country("cf", "+236", "أفريقي أوسط", Res.drawable.cf),
    Country("td", "+235", "تشادي", Res.drawable.td),
    Country("cl", "+56", "شيلي", Res.drawable.cl),
    Country("cn", "+86", "صيني", Res.drawable.cn),
    Country("cx", "+61", "كريسماسي", Res.drawable.cx),
    Country("cc", "+61", "كوكوسي", Res.drawable.cc),
    Country("co", "+57", "كولومبي", Res.drawable.co),
    Country("km", "+269", "قمري", Res.drawable.km),
    Country("cg", "+242", "كونغولي", Res.drawable.cg),
    Country("cd", "+243", "كونغولي ديمقراطي", Res.drawable.cd),
    Country("ck", "+682", "كوكي", Res.drawable.ck),
    Country("cr", "+506", "كوستاريكي", Res.drawable.cr),
    Country("hr", "+385", "كرواتي", Res.drawable.hr),
    Country("cu", "+53", "كوبي", Res.drawable.cu),
    Country("cw", "+599", "كوراساوي", Res.drawable.cw),
    Country("cy", "+357", "قبرصي", Res.drawable.cy),
    Country("cyp", "+357", "قبرصي", Res.drawable.cy),
    Country("cz", "+420", "تشيكي", Res.drawable.cz),
    Country("ci", "+225", "إيفواري", Res.drawable.ci),
    Country("dk", "+45", "دنماركي", Res.drawable.dk),
    Country("dj", "+253", "جيبوتي", Res.drawable.dj),
    Country("dm", "+1", "دومينيكي", Res.drawable.dm),
    Country("do", "+1", "دومينيكي", Res.drawable.ic_do),
    Country("ec", "+593", "إكوادوري", Res.drawable.ec),
    Country("eg", "+20", "مصري", Res.drawable.eg),
    Country("sv", "+503", "سلفادوري", Res.drawable.sv),
    Country("gq", "+240", "غيني استوائي", Res.drawable.gq),
    Country("er", "+291", "إريتري", Res.drawable.er),
    Country("ee", "+372", "إستوني", Res.drawable.ee),
    Country("sz", "+268", "سوازيلندي", Res.drawable.sz),
    Country("et", "+251", "إثيوبي", Res.drawable.et),
    Country("fk", "+500", "فوكلاندي", Res.drawable.fk),
    Country("fo", "+298", "فاروي", Res.drawable.fo),
    Country("fj", "+679", "فيجي", Res.drawable.fj),
    Country("fi", "+358", "فنلندي", Res.drawable.fi),
    Country("fr", "+33", "فرنسي", Res.drawable.fr),
    Country("gf", "+594", "غياني فرنسي", Res.drawable.gf),
    Country("pf", "+689", "بولينيزي فرنسي", Res.drawable.pf),
    Country("tf", "+262", "فرنسي جنوبي", Res.drawable.tf),
    Country("ga", "+241", "غابوني", Res.drawable.ga),
    Country("gm", "+220", "غامبي", Res.drawable.gm),
    Country("ge", "+995", "جورجي", Res.drawable.ge),
    Country("de", "+49", "ألماني", Res.drawable.de),
    Country("de", "+49", "ألماني", Res.drawable.de),
    Country("gh", "+233", "غاني", Res.drawable.gh),
    Country("gi", "+350", "جبل طارقي", Res.drawable.gi),
    Country("gr", "+30", "يوناني", Res.drawable.gr),
    Country("gr", "+30", "يوناني", Res.drawable.gr),
    Country("gl", "+299", "جرينلاندي", Res.drawable.gl),
    Country("gd", "+1", "غرينادي", Res.drawable.gd),
    Country("gp", "+590", "غوادلوبي", Res.drawable.gp),
    Country("gu", "+1", "غوامي", Res.drawable.gu),
    Country("gt", "+502", "غواتيمالي", Res.drawable.gt),
    Country("gg", "+44", "جيرنزي", Res.drawable.gg),
    Country("gn", "+224", "غيني", Res.drawable.gn),
    Country("gw", "+245", "غيني بيساوي", Res.drawable.gw),
    Country("gy", "+592", "غياني", Res.drawable.gy),
    Country("ht", "+509", "هايتي", Res.drawable.ht),
    Country("hm", "+672", "هيردي", Res.drawable.hm),
    Country("va", "+379", "فاتيكاني", Res.drawable.va),
    Country("hn", "+504", "هندوراسي", Res.drawable.hn),
    Country("hk", "+852", "هونغ كونغي", Res.drawable.hk),
    Country("hu", "+36", "مجري", Res.drawable.hu),
    Country("is", "+354", "آيسلندي", Res.drawable.`is`),
    Country("in", "+91", "هندي", Res.drawable.`in`),
    Country("id", "+62", "إندونيسي", Res.drawable.id),
    Country("ir", "+98", "إيراني", Res.drawable.ir),
    Country("iq", "+964", "عراقي", Res.drawable.iq),
    Country("ie", "+353", "أيرلندي", Res.drawable.ie),
    Country("im", "+44", "ماني", Res.drawable.im),
    Country("il", "+972", "إسرائيلي", Res.drawable.il),
    Country("it", "+39", "إيطالي", Res.drawable.it),
    Country("jm", "+1", "جامايكي", Res.drawable.jm),
    Country("jp", "+81", "ياباني", Res.drawable.jp),
    Country("je", "+44", "جيرزي", Res.drawable.je),
    Country("jo", "+962", "أردني", Res.drawable.jo),
    Country("kz", "+7", "كازاخستاني", Res.drawable.kz),
    Country("ke", "+254", "كيني", Res.drawable.ke),
    Country("ki", "+686", "كيريباتي", Res.drawable.ki),
    Country("kp", "+850", "كوري شمالي", Res.drawable.kp),
    Country("kr", "+82", "كوري جنوبي", Res.drawable.kr),
    Country("kw", "+965", "كويتي", Res.drawable.kw),
    Country("kg", "+996", "قيرغيزي", Res.drawable.kg),
    Country("la", "+856", "لاوسي", Res.drawable.la),
    Country("lv", "+371", "لاتفي", Res.drawable.lv),
    Country("lb", "+961", "لبناني", Res.drawable.lb),
    Country("ls", "+266", "ليسوتي", Res.drawable.ls),
    Country("lr", "+231", "ليبيري", Res.drawable.lr),
    Country("ly", "+218", "ليبي", Res.drawable.ly),
    Country("li", "+423", "ليختنشتايني", Res.drawable.li),
    Country("lt", "+370", "ليتواني", Res.drawable.lt),
    Country("lu", "+352", "لوكسمبورغي", Res.drawable.lu),
    Country("mo", "+853", "ماكاوي", Res.drawable.mo),
    Country("mg", "+261", "مدغشقري", Res.drawable.mg),
    Country("mw", "+265", "مالاوي", Res.drawable.mw),
    Country("my", "+60", "ماليزي", Res.drawable.my),
    Country("mv", "+960", "مالديفي", Res.drawable.mv),
    Country("ml", "+223", "مالي", Res.drawable.ml),
    Country("mt", "+356", "مالطي", Res.drawable.mt),
    Country("mh", "+692", "مارشالي", Res.drawable.mh),
    Country("mq", "+596", "مارتينيكي", Res.drawable.mq),
    Country("mr", "+222", "موريتاني", Res.drawable.mr),
    Country("mu", "+230", "موريشيوسي", Res.drawable.mu),
    Country("yt", "+262", "مايوتي", Res.drawable.yt),
    Country("mx", "+52", "مكسيكي", Res.drawable.mx),
    Country("fm", "+691", "ميكرونيزي", Res.drawable.fm),
    Country("md", "+373", "مولدوفي", Res.drawable.md),
    Country("mc", "+377", "موناكي", Res.drawable.mc),
    Country("mn", "+976", "منغولي", Res.drawable.mn),
    Country("me", "+382", "مونتينيغري", Res.drawable.me),
    Country("ms", "+1", "مونتسيراتي", Res.drawable.ms),
    Country("ma", "+212", "مغربي", Res.drawable.ma),
    Country("mz", "+258", "موزمبيقي", Res.drawable.mz),
    Country("mm", "+95", "ميانماري", Res.drawable.mm),
    Country("na", "+264", "ناميبي", Res.drawable.na),
    Country("nr", "+674", "ناورو", Res.drawable.nr),
    Country("np", "+977", "نيبالي", Res.drawable.np),
    Country("nl", "+31", "هولندي", Res.drawable.nl),
    Country("nc", "+687", "كاليدوني جديد", Res.drawable.nc),
    Country("nz", "+64", "نيوزيلندي", Res.drawable.nz),
    Country("ni", "+505", "نيكاراغوي", Res.drawable.ni),
    Country("ne", "+227", "نيجري", Res.drawable.ne),
    Country("ng", "+234", "نيجيري", Res.drawable.ng),
    Country("nu", "+683", "نييوي", Res.drawable.nu),
    Country("nf", "+672", "نورفولكي", Res.drawable.nf),
    Country("mp", "+1", "مارياني شمالي", Res.drawable.mp),
    Country("no", "+47", "نرويجي", Res.drawable.no),
    Country("om", "+968", "عماني", Res.drawable.om),
    Country("pk", "+92", "باكستاني", Res.drawable.pk),
    Country("pw", "+680", "بالاوي", Res.drawable.pw),
    Country("ps", "+970", "فلسطيني", Res.drawable.ps),
    Country("pa", "+507", "بنيمي", Res.drawable.pa),
    Country("pg", "+675", "بابوا غيني جديد", Res.drawable.pg),
    Country("py", "+595", "باراغواياني", Res.drawable.py),
    Country("pe", "+51", "بيروفي", Res.drawable.pe),
    Country("ph", "+63", "فلبيني", Res.drawable.ph),
    Country("pn", "+870", "بيتكايرني", Res.drawable.pn),
    Country("pl", "+48", "بولندي", Res.drawable.pl),
    Country("pt", "+351", "برتغالي", Res.drawable.pt),
    Country("pr", "+1", "بورتوريكي", Res.drawable.pr),
    Country("qa", "+974", "قطري", Res.drawable.qa),
    Country("re", "+262", "ريونيوني", Res.drawable.re),
    Country("ro", "+40", "روماني", Res.drawable.ro),
    Country("ru", "+7", "روسي", Res.drawable.ru),
    Country("rw", "+250", "رواندي", Res.drawable.rw),
    Country("bl", "+590", "سان بارتيلمي", Res.drawable.bl),
    Country("sh", "+290", "سانت هيليني", Res.drawable.sh),
    Country("kn", "+1", "سانت كيتسي", Res.drawable.kn),
    Country("lc", "+1", "سانت لوسي", Res.drawable.lc),
    Country("mf", "+590", "سانت مارتني فرنسي", Res.drawable.mf),
    Country("pm", "+508", "سان بييري", Res.drawable.pm),
    Country("vc", "+1", "سانت فنسنتي", Res.drawable.vc),
    Country("ws", "+685", "ساموي", Res.drawable.ws),
    Country("sm", "+378", "سان ماريني", Res.drawable.sm),
    Country("st", "+239", "ساو تومي", Res.drawable.st),
    Country("sa", "+966", "سعودي", Res.drawable.sa),
    Country("sn", "+221", "سنغالي", Res.drawable.sn),
    Country("rs", "+381", "صربي", Res.drawable.rs),
    Country("sc", "+248", "سيشلي", Res.drawable.sc),
    Country("sl", "+232", "سيراليوني", Res.drawable.sl),
    Country("sg", "+65", "سنغافوري", Res.drawable.sg),
    Country("sx", "+1", "سينت مارتني هولندي", Res.drawable.sx),
    Country("sk", "+421", "سلوفاكي", Res.drawable.sk),
    Country("si", "+386", "سلوفيني", Res.drawable.si),
    Country("sb", "+677", "سليماني", Res.drawable.sb),
    Country("so", "+252", "صومالي", Res.drawable.so),
    Country("za", "+27", "جنوب أفريقي", Res.drawable.za),
    Country("gs", "+500", "ساندويتشي جنوبي", Res.drawable.gs),
    Country("ss", "+211", "جنوب سوداني", Res.drawable.ss),
    Country("es", "+34", "إسباني", Res.drawable.es),
    Country("lk", "+94", "سريلانكي", Res.drawable.lk),
    Country("sd", "+249", "سوداني", Res.drawable.sd),
    Country("sr", "+597", "سورينامي", Res.drawable.sr),
    Country("sj", "+47", "سفالباردي", Res.drawable.sj),
    Country("se", "+46", "سويدي", Res.drawable.se),
    Country("se", "+46", "سويدي", Res.drawable.se),
    Country("ch", "+41", "سويسري", Res.drawable.ch),
    Country("sy", "+963", "سوري", Res.drawable.sy),
    Country("tw", "+886", "تايواني", Res.drawable.tw),
    Country("tj", "+992", "طاجيكي", Res.drawable.tj),
    Country("tz", "+255", "تنزاني", Res.drawable.tz),
    Country("th", "+66", "تايلاندي", Res.drawable.th),
    Country("tl", "+670", "تيموري شرقي", Res.drawable.tl),
    Country("tg", "+228", "توغولي", Res.drawable.tg),
    Country("tk", "+690", "توكيلاوي", Res.drawable.tk),
    Country("to", "+676", "تونغي", Res.drawable.to),
    Country("tt", "+1", "ترينيدادي", Res.drawable.tt),
    Country("tn", "+216", "تونسي", Res.drawable.tn),
    Country("tr", "+90", "تركي", Res.drawable.tr),
    Country("tm", "+993", "تركماني", Res.drawable.tm),
    Country("tc", "+1", "تركي وكايكوسي", Res.drawable.tc),
    Country("tv", "+688", "توفالوي", Res.drawable.tv),
    Country("ug", "+256", "أوغندي", Res.drawable.ug),
    Country("ua", "+380", "أوكراني", Res.drawable.ua),
    Country("ae", "+971", "إماراتي", Res.drawable.ae),
    Country("gb", "+44", "بريطاني", Res.drawable.gb),
    Country("um", "+1", "أمريكي نائي", Res.drawable.um),
    Country("us", "+1", "أمريكي", Res.drawable.us),
    Country("uy", "+598", "أوروغوياني", Res.drawable.uy),
    Country("uz", "+998", "أوزبكي", Res.drawable.uz),
    Country("vu", "+678", "فانواتي", Res.drawable.vu),
    Country("ve", "+58", "فنزويلي", Res.drawable.ve),
    Country("vn", "+84", "فيتنامي", Res.drawable.vn),
    Country("vg", "+1", "فيرجيني بريطاني", Res.drawable.vg),
    Country("vi", "+1", "فيرجيني أمريكي", Res.drawable.vi),
    Country("wf", "+681", "واليسي وفوتوني", Res.drawable.wf),
    Country("eh", "+212", "صحراوي", Res.drawable.eh),
    Country("ye", "+967", "يمني", Res.drawable.ye),
    Country("zm", "+260", "زامبي", Res.drawable.zm),
    Country("zw", "+263", "زيمبابوي", Res.drawable.zw)
).sortedWith(compareBy<Country> { it.code !in listOf("ir", "tr", "iq") }
    .thenBy { it.name })
