package Pr22.Extension;

import java.util.HashMap;

public class CountryCode {

    static final CountryCode[] values = {
        new CountryCode("AFG", "Afghanistan"),
        new CountryCode("ALA", "Åland Islands"),
        new CountryCode("ALB", "Albania"),
        new CountryCode("DZA", "Algeria"),
        new CountryCode("ASM", "American Samoa"),
        new CountryCode("AND", "Andorra"),
        new CountryCode("AGO", "Angola"),
        new CountryCode("AIA", "Anguilla"),
        new CountryCode("ATA", "Antarctica"),
        new CountryCode("ATG", "Antigua and Barbuda"),
        new CountryCode("ARG", "Argentina"),
        new CountryCode("ARM", "Armenia"),
        new CountryCode("ABW", "Aruba"),
        new CountryCode("AUS", "Australia"),
        new CountryCode("AUT", "Austria"),
        new CountryCode("AZE", "Azerbaijan"),
        new CountryCode("BHS", "Bahamas"),
        new CountryCode("BHR", "Bahrain"),
        new CountryCode("BGD", "Bangladesh"),
        new CountryCode("BRB", "Barbados"),
        new CountryCode("BLR", "Belarus"),
        new CountryCode("BEL", "Belgium"),
        new CountryCode("BLZ", "Belize"),
        new CountryCode("BEN", "Benin"),
        new CountryCode("BMU", "Bermuda"),
        new CountryCode("BTN", "Bhutan"),
        new CountryCode("BOL", "Bolivia"),
        new CountryCode("BES", "Bonaire, Sint Eustatius and Saba"),
        new CountryCode("BIH", "Bosnia and Herzegovina"),
        new CountryCode("BWA", "Botswana"),
        new CountryCode("BVT", "Bouvet Island"),
        new CountryCode("BRA", "Brazil"),
        new CountryCode("IOT", "British Indian Ocean Territory"),
        new CountryCode("BRN", "Brunei Darussalam"),
        new CountryCode("BGR", "Bulgaria"),
        new CountryCode("BFA", "Burkina Faso"),
        new CountryCode("BDI", "Burundi"),
        new CountryCode("CPV", "Cabo Verde"),
        new CountryCode("KHM", "Cambodia"),
        new CountryCode("CMR", "Cameroon"),
        new CountryCode("CAN", "Canada"),
        new CountryCode("CYM", "Cayman Islands"),
        new CountryCode("CAF", "Central African Republic"),
        new CountryCode("TCD", "Chad"),
        new CountryCode("CHL", "Chile"),
        new CountryCode("CHN", "China"),
        new CountryCode("CXR", "Christmas Island"),
        new CountryCode("CCK", "Cocos (Keeling) Islands"),
        new CountryCode("COL", "Colombia"),
        new CountryCode("COM", "Comoros"),
        new CountryCode("COD", "Democratic Republic of the Congo"),
        new CountryCode("COG", "Congo"),
        new CountryCode("COK", "Cook Islands"),
        new CountryCode("CRI", "Costa Rica"),
        new CountryCode("CIV", "Côte d'Ivoire"),
        new CountryCode("HRV", "Croatia"),
        new CountryCode("CUB", "Cuba"),
        new CountryCode("CUW", "Curaçao"),
        new CountryCode("CYP", "Cyprus"),
        new CountryCode("CZE", "Czechia"),
        new CountryCode("DNK", "Denmark"),
        new CountryCode("DJI", "Djibouti"),
        new CountryCode("DMA", "Dominica"),
        new CountryCode("DOM", "Dominican Republic"),
        new CountryCode("ECU", "Ecuador"),
        new CountryCode("EGY", "Egypt"),
        new CountryCode("SLV", "El Salvador"),
        new CountryCode("GNQ", "Equatorial Guinea"),
        new CountryCode("ERI", "Eritrea"),
        new CountryCode("EST", "Estonia"),
        new CountryCode("SWZ", "Eswatini"),
        new CountryCode("ETH", "Ethiopia"),
        new CountryCode("FLK", "Falkland Islands (Malvinas)"),
        new CountryCode("FRO", "Faroe Islands"),
        new CountryCode("FJI", "Fiji"),
        new CountryCode("FIN", "Finland"),
        new CountryCode("FRA", "France"),
        new CountryCode("GUF", "French Guiana"),
        new CountryCode("PYF", "French Polynesia"),
        new CountryCode("ATF", "French Southern Territories"),
        new CountryCode("GAB", "Gabon"),
        new CountryCode("GMB", "Gambia"),
        new CountryCode("GEO", "Georgia"),
        new CountryCode("D", "Germany"),
        new CountryCode("GHA", "Ghana"),
        new CountryCode("GIB", "Gibraltar"),
        new CountryCode("GRC", "Greece"),
        new CountryCode("GRL", "Greenland"),
        new CountryCode("GRD", "Grenada"),
        new CountryCode("GLP", "Guadeloupe"),
        new CountryCode("GUM", "Guam"),
        new CountryCode("GTM", "Guatemala"),
        new CountryCode("GGY", "Guernsey"),
        new CountryCode("GIN", "Guinea"),
        new CountryCode("GNB", "Guinea-Bissau"),
        new CountryCode("GUY", "Guyana"),
        new CountryCode("HTI", "Haiti"),
        new CountryCode("HMD", "Heard and McDonald Islands"),
        new CountryCode("VAT", "Holy See (Vatican City State)"),
        new CountryCode("HND", "Honduras"),
        new CountryCode("HKG", "Hong Kong"),
        new CountryCode("HUN", "Hungary"),
        new CountryCode("ISL", "Iceland"),
        new CountryCode("IND", "India"),
        new CountryCode("IDN", "Indonesia"),
        new CountryCode("IRN", "Islamic Republic of Iran"),
        new CountryCode("IRQ", "Iraq"),
        new CountryCode("IRL", "Ireland"),
        new CountryCode("IMN", "Isle of Man"),
        new CountryCode("ISR", "Israel"),
        new CountryCode("ITA", "Italy"),
        new CountryCode("JAM", "Jamaica"),
        new CountryCode("JPN", "Japan"),
        new CountryCode("JEY", "Jersey"),
        new CountryCode("JOR", "Jordan"),
        new CountryCode("KAZ", "Kazakhstan"),
        new CountryCode("KEN", "Kenya"),
        new CountryCode("KIR", "Kiribati"),
        new CountryCode("PRK", "Democratic People's Republic of Korea"),
        new CountryCode("KOR", "Republic of Korea"),
        new CountryCode("KWT", "Kuwait"),
        new CountryCode("KGZ", "Kyrgyzstan"),
        new CountryCode("LAO", "Lao People's Democratic Republic"),
        new CountryCode("LVA", "Latvia"),
        new CountryCode("LBN", "Lebanon"),
        new CountryCode("LSO", "Lesotho"),
        new CountryCode("LBR", "Liberia"),
        new CountryCode("LBY", "Libya"),
        new CountryCode("LIE", "Liechtenstein"),
        new CountryCode("LTU", "Lithuania"),
        new CountryCode("LUX", "Luxembourg"),
        new CountryCode("MAC", "Macao"),
        new CountryCode("MDG", "Madagascar"),
        new CountryCode("MWI", "Malawi"),
        new CountryCode("MYS", "Malaysia"),
        new CountryCode("MDV", "Maldives"),
        new CountryCode("MLI", "Mali"),
        new CountryCode("MLT", "Malta"),
        new CountryCode("MHL", "Marshall Islands"),
        new CountryCode("MTQ", "Martinique"),
        new CountryCode("MRT", "Mauritania"),
        new CountryCode("MUS", "Mauritius"),
        new CountryCode("MYT", "Mayotte"),
        new CountryCode("MEX", "Mexico"),
        new CountryCode("FSM", "Federated States of Micronesia"),
        new CountryCode("MDA", "Republic of Moldova"),
        new CountryCode("MCO", "Monaco"),
        new CountryCode("MNG", "Mongolia"),
        new CountryCode("MNE", "Montenegro"),
        new CountryCode("MSR", "Montserrat"),
        new CountryCode("MAR", "Morocco"),
        new CountryCode("MOZ", "Mozambique"),
        new CountryCode("MMR", "Myanmar"),
        new CountryCode("NAM", "Namibia"),
        new CountryCode("NRU", "Nauru"),
        new CountryCode("NPL", "Nepal"),
        new CountryCode("NLD", "Netherlands"),
        new CountryCode("NCL", "New Caledonia"),
        new CountryCode("NZL", "New Zealand"),
        new CountryCode("NIC", "Nicaragua"),
        new CountryCode("NER", "Niger"),
        new CountryCode("NGA", "Nigeria"),
        new CountryCode("NIU", "Niue"),
        new CountryCode("NFK", "Norfolk Island"),
        new CountryCode("MKD", "North Macedonia"),
        new CountryCode("MNP", "Northern Mariana Islands"),
        new CountryCode("NOR", "Norway"),
        new CountryCode("OMN", "Oman"),
        new CountryCode("PAK", "Pakistan"),
        new CountryCode("PLW", "Palau"),
        new CountryCode("PSE", "State of Palestine"),
        new CountryCode("PAN", "Panama"),
        new CountryCode("PNG", "Papua New Guinea"),
        new CountryCode("PRY", "Paraguay"),
        new CountryCode("PER", "Peru"),
        new CountryCode("PHL", "Philippines"),
        new CountryCode("PCN", "Pitcairn"),
        new CountryCode("POL", "Poland"),
        new CountryCode("PRT", "Portugal"),
        new CountryCode("PRI", "Puerto Rico"),
        new CountryCode("QAT", "Qatar"),
        new CountryCode("REU", "Réunion"),
        new CountryCode("ROU", "Romania"),
        new CountryCode("RUS", "Russian Federation"),
        new CountryCode("RWA", "Rwanda"),
        new CountryCode("BLM", "Saint Barthélemy"),
        new CountryCode("SHN", "Saint Helena"),
        new CountryCode("KNA", "Saint Kitts and Nevis"),
        new CountryCode("LCA", "Saint Lucia"),
        new CountryCode("MAF", "Saint Martin (French)"),
        new CountryCode("SPM", "Saint Pierre and Miquelon"),
        new CountryCode("VCT", "Saint Vincent and the Grenadines"),
        new CountryCode("WSM", "Samoa"),
        new CountryCode("SMR", "San Marino"),
        new CountryCode("STP", "Sao Tome and Principe"),
        new CountryCode("SAU", "Saudi Arabia"),
        new CountryCode("SEN", "Senegal"),
        new CountryCode("SRB", "Serbia"),
        new CountryCode("SYC", "Seychelles"),
        new CountryCode("SLE", "Sierra Leone"),
        new CountryCode("SGP", "Singapore"),
        new CountryCode("SXM", "Sint Maarten (Dutch)"),
        new CountryCode("SVK", "Slovakia"),
        new CountryCode("SVN", "Slovenia"),
        new CountryCode("SLB", "Solomon Islands"),
        new CountryCode("SOM", "Somalia"),
        new CountryCode("ZAF", "South Africa"),
        new CountryCode("SGS", "South Georgia and the South Sandwich Islands"),
        new CountryCode("SSD", "South Sudan"),
        new CountryCode("ESP", "Spain"),
        new CountryCode("LKA", "Sri Lanka"),
        new CountryCode("SDN", "Sudan"),
        new CountryCode("SUR", "Suriname"),
        new CountryCode("SJM", "Svalbard and Jan Mayen Islands"),
        new CountryCode("SWE", "Sweden"),
        new CountryCode("CHE", "Switzerland"),
        new CountryCode("SYR", "Syrian Arab Republic"),
        new CountryCode("TWN", "Taiwan, Republic of China"),
        new CountryCode("TJK", "Tajikistan"),
        new CountryCode("TZA", "United Republic of Tanzania"),
        new CountryCode("THA", "Thailand"),
        new CountryCode("TLS", "Timor-Leste"),
        new CountryCode("TGO", "Togo"),
        new CountryCode("TKL", "Tokelau"),
        new CountryCode("TON", "Tonga"),
        new CountryCode("TTO", "Trinidad and Tobago"),
        new CountryCode("TUN", "Tunisia"),
        new CountryCode("TUR", "Turkey"),
        new CountryCode("TKM", "Turkmenistan"),
        new CountryCode("TCA", "Turks and Caicos Islands"),
        new CountryCode("TUV", "Tuvalu"),
        new CountryCode("UGA", "Uganda"),
        new CountryCode("UKR", "Ukraine"),
        new CountryCode("ARE", "United Arab Emirates"),
        new CountryCode("GBR", "United Kingdom"),
        new CountryCode("UMI", "United States Minor Outlying Islands"),
        new CountryCode("USA", "United States of America"),
        new CountryCode("URY", "Uruguay"),
        new CountryCode("UZB", "Uzbekistan"),
        new CountryCode("VUT", "Vanuatu"),
        new CountryCode("VEN", "Venezuela"),
        new CountryCode("VNM", "Viet Nam"),
        new CountryCode("VGB", "Virgin Islands (British)"),
        new CountryCode("VIR", "Virgin Islands (U.S.)"),
        new CountryCode("WLF", "Wallis and Futuna Islands"),
        new CountryCode("ESH", "Western Sahara"),
        new CountryCode("YEM", "Yemen"),
        new CountryCode("ZMB", "Zambia"),
        new CountryCode("ZWE", "Zimbabwe"),
        new CountryCode("GBD", "British Overseas Territories Citizen"),
        new CountryCode("GBN", "British National (Overseas)"),
        new CountryCode("GBO", "British Overseas Citizen"),
        new CountryCode("GBP", "British Protected Person"),
        new CountryCode("GBS", "British Subject"),
        new CountryCode("UNO", "United Nations"),
        new CountryCode("UNA", "United Nations"),
        new CountryCode("UNK", "Kosovo (United Nations)"),
        new CountryCode("XBA", "African Development Bank"),
        new CountryCode("XIM", "African Export-Import Bank"),
        new CountryCode("XCC", "Caribbean Community"),
        new CountryCode("XCE", "Council of Europe"),
        new CountryCode("XCO", "Common Market for Eastern and Southern Africa"),
        new CountryCode("XEC", "Economic Community of West African States"),
        new CountryCode("XPO", "Interpol"),
        new CountryCode("XOM", "Sovereign Military Order of Malta"),
        new CountryCode("XDC", "Southern African Development Community"),
        new CountryCode("XXA", "Stateless"),
        new CountryCode("XXB", "Refugee"),
        new CountryCode("XXC", "Refugee"),
        new CountryCode("XXX", "Unspecified"),
        new CountryCode("EUE", "European Union"),
        new CountryCode("RKS", "Republic of Kosovo"),
        new CountryCode("XCT", "North Cyprus"),
        new CountryCode("ANT", "Netherlands Antilles"),
        new CountryCode("NTZ", "Neutral Zone"),
        new CountryCode("SCG", "Serbia and Montenegro"),
        new CountryCode("YUG", "Yugoslavia"),
        new CountryCode("FXX", "France, Metropolitan"),};
    private String name;
    private String code;
    static final HashMap<String, String> countries_code = new HashMap<String, String>();

    private CountryCode(String code, String name) {
        this.code = code;
        this.name = name;
    }

    static {
        for (int i = 0; i < values.length; i++) {
            CountryCode cc = values[i];
            countries_code.put(cc.getCode(), cc.getName());
        }
    }

    String getCode() {
        return code;
    }

    String getName() {
        return name;
    }

    public static String getName(String code) {
        String value;
        value = countries_code.get(code);
        return value != null ? value : "";
    }
}
