name: Package Manifest Desktop App
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  package:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Package MSI (Windows)
        run: ./gradlew packageReleaseMsi

      - name: Debug build output
        run: Get-ChildItem -Recurse -Include *.msi,*.exe composeApp\build\compose | Select-Object FullName
        shell: pwsh

      - name: Rename MSI
        run: |
          $msi = Get-ChildItem -Recurse -Include *.msi composeApp\build\compose\binaries\main-release
          Rename-Item $msi.FullName "manifest.msi"
        shell: pwsh

      - name: Upload Artifacts to Remote Repo
        uses: softprops/action-gh-release@v2
        with:
          repository: RoonyShekho09/Manifest-Desktop-Releases
          generate_release_notes: true
          files: |
            composeApp/build/compose/binaries/main-release/**/*.msi
            composeApp/build/compose/binaries/main-release/**/*.exe
          token: ${{ secrets.RELEASE_PAT }}